markdown: kramdown
baseurl: /template-portfolio-b
website-title: Website title
exclude: ['README.md', '.gitignore']
permalink: pretty
google-api-key:
analytics :
  provider : google
  google :
    tracking_id :
